name: Build iohook

on:
  workflow_dispatch:


jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all --openssl_fips=''

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Windows Prebuilds
          path: prebuilds

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: macOS Prebuilds
          path: prebuilds

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt-get update
      - name: Install dependencies (Ubuntu)
        run: sudo apt-get install libxtst-dev

      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Linux (Ubuntu) Prebuilds
          path: prebuilds
